### ISSUE TITLE
Overlapping requests cause errors (during testing)

### ISSUE THREAD

**Issue by kenhahn85** [tmenier/Flurl#154]
Using `Flurl.Http` 1.0.3, I'm using `HttpTest` in uni tests, and one of my tests executes a number of overlapping HTTP requests. On this test, there appears to be race conditions at work. Here are some of the various stack traces I've seen:

Referring to `FlurlHttpException`,
```
System.NullReferenceException : Object reference not set to an instance of an object.
```

```
      System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
           at System.Collections.Generic.List`1.Add(T item)
        C:\projects\flurl\src\Flurl.Http.Shared\FlurlHttp.cs(63,0): at Flurl.Http.FlurlHttp.HandleEventAsync(Action`1 syncHandler, Func`2 asyncHandler, HttpCall call)
        C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs(59,0): at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\flurl\src\Flurl.Http.Shared\FlurlClient.cs(128,0): at Flurl.Http.FlurlClient.<SendAsync>d__28.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        C:\projects\flurl\src\Flurl.Http.Shared\HttpResponseMessageExtensions.cs(26,0): at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext()
```

**Comment by tmenier** [comment]
Please upgrade to the latest Flurl.Http. 1.1 was all about concurrency with HttpTest.

**Comment by kenhahn85** [comment]
I've upgraded to 1.1.1, and I get a different error that also seems concurrency-related:

```
Flurl.Http.FlurlHttpException: Request to https://xyz.com failed. Collection was modified; enumeration operation may not execute. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Flurl.Http.Testing.HttpTest.GetNextResponse() in C:\projects\flurl\src\Flurl.Http.Shared\Testing\HttpTest.cs:line 103
   at Flurl.Http.Testing.FakeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\projects\flurl\src\Flurl.Http.Shared\Testing\FakeHttpMessageHandler.cs:line 22
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs:line 37
   --- End of inner exception stack trace ---
   at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.FlurlClient.<SendAsync>d__28.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\FlurlClient.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\HttpResponseMessageExtensions.cs:line 26
```

**Comment by Jacob-McKay** [comment]
I was on 1.0.x and had to keep my xunit unit tests from running in parallel with something like: [Collection("Non-Threadsafe HttpTest Tests")]

Upgraded to 1.1.1 and they run altogether now, happy days!

**Comment by tmenier** [comment]
@kenhahn85 Can you post the code for your test?

**Comment by tmenier** [comment]
Closing due to lack of response. If you still think there's an issue here, feel free to re-open and explain.
