### ISSUE TITLE
Flurl Http Testing framework fails on deserializing default (empty) response more than once

### ISSUE THREAD

**Issue by AuthorProxy** [tmenier/Flurl#175]
Given next environment:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoFixture" version="3.50.2" targetFramework="net461" />
  <package id="AutoFixture.AutoMoq" version="3.50.2" targetFramework="net461" />
  <package id="AutoFixture.Xunit2" version="3.50.2" targetFramework="net461" />
  <package id="Castle.Core" version="4.0.0" targetFramework="net461" />
  <package id="FluentAssertions" version="4.19.2" targetFramework="net461" />
  <package id="Flurl" version="2.3.0" targetFramework="net461" />
  <package id="Flurl.Http" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Win32.Primitives" version="4.0.1" targetFramework="net461" />
  <package id="Moq" version="4.7.8" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.0.0" targetFramework="net461" />
  <package id="System.Globalization" version="4.0.11" targetFramework="net461" />
  <package id="System.IO.FileSystem" version="4.0.1" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.0.1" targetFramework="net461" />
  <package id="System.Linq" version="4.1.0" targetFramework="net461" />
  <package id="System.Net.Http" version="4.1.0" targetFramework="net461" />
  <package id="System.Reflection.TypeExtensions" version="4.1.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.2.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.0.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.0.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.1.0" targetFramework="net461" />
  <package id="System.Text.Encoding.CodePages" version="4.0.1" targetFramework="net461" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net461" />
  <package id="xunit.assert" version="2.2.0" targetFramework="net461" />
  <package id="xunit.core" version="2.2.0" targetFramework="net461" />
  <package id="xunit.extensibility.core" version="2.2.0" targetFramework="net461" />
  <package id="xunit.extensibility.execution" version="2.2.0" targetFramework="net461" />
</packages>
```

Flurl.Http.Testing gives error each time I try to run next tests:
```
using System.Net.Http;
using Flurl.Http.Testing;
using Ploeh.AutoFixture;
using Ploeh.AutoFixture.AutoMoq;
using QP8.Infrastructure.Logging.Factories;
using QP8.Infrastructure.Logging.PrtgMonitoring;
using QP8.Infrastructure.Tests.Infrastructure.Specimens;
using Xunit;

namespace QP8.Infrastructure.Tests.PrtgMonitoringTests
{
    public class PrtgMonitoringServiceTests
    {
        private readonly IFixture _fixture;
        private readonly HttpTest _httpTest;

        private const string ErrorRequestData = @"
<prtg>
    <text>test success message</text>
    <result><channel>MyChannel</channel><value>17</value></result>
    <result><channel>AnotherChannel</channel><value>31</value></result>
</prtg>";

        private const string SuccessRequestData = @"
<prtg>
    <text>test success message</text>
    <result><channel>MyChannel</channel><value>17</value></result>
    <result><channel>AnotherChannel</channel><value>31</value></result>
</prtg>";

        public PrtgMonitoringServiceTests()
        {
            _fixture = new Fixture().Customize(new AutoConfiguredMoqCustomization()).Customize(new MultipleCustomization());
            _fixture.Customizations.Add(new PrtgMonitoringServiceSpecimenBuilder());
            _httpTest = new HttpTest();
            LogProvider.LogFactory = new NullLogFactory();
        }

        [Fact]
        public async void PrtgMonitoring_SendStringGetRequest_SendExpectedData()
        {
            // Fixture setup
            var sut = _fixture.Create<PrtgMonitoringService>();

            // Exercise system
            await sut.SendStringGetRequest(SuccessRequestData);

            // Verify outcome
            _httpTest
                .ShouldHaveMadeACall()
                .WithVerb(HttpMethod.Get)
                .WithQueryParamValue("Content", SuccessRequestData);
        }

        [Fact]
        public async void PrtgMonitoring_SendStringPostRequest_SendExpectedData()
        {
            // Fixture setup
            var sut = _fixture.Create<PrtgMonitoringService>();

            // Exercise system
            await sut.SendStringPostRequest(ErrorRequestData);

            // Verify outcome
            _httpTest
                .ShouldHaveMadeACall()
                .WithVerb(HttpMethod.Post)
                .WithoutQueryParams()
                .WithRequestBody(SuccessRequestData);
        }
    }
}
```
When i run this tests in different class in parallel, or manually one by one - everything works as expected,
but when they started sequantially on one run, next error appears:
```
Flurl.Http.FlurlHttpException
Request to http://mscmonitor01:5050/qp.articlescheduler.mscdev02?Content=%0D%0A%3Cprtg%3E%0D%0A%20%20%20%20%3Ctext%3Etest%20success%20message%3C%2Ftext%3E%0D%0A%20%20%20%20%3Cresult%3E%3Cchannel%3EMyChannel%3C%2Fchannel%3E%3Cvalue%3E17%3C%2Fvalue%3E%3C%2Fresult%3E%0D%0A%20%20%20%20%3Cresult%3E%3Cchannel%3EAnotherChannel%3C%2Fchannel%3E%3Cvalue%3E31%3C%2Fvalue%3E%3C%2Fresult%3E%0D%0A%3C%2Fprtg%3E failed. Stream was not readable.
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\HttpResponseMessageExtensions.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at QP8.Infrastructure.Logging.PrtgMonitoring.PrtgMonitoringService.<SendStringGetRequest>d__6.MoveNext() in C:\ProxyDocuments\Projects\QP\QP8.Infrastructure.Logging.PrtgMonitoring\PrtgMonitoringService.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at QP8.Infrastructure.Tests.PrtgMonitoringTests.PrtgMonitoringServiceTests.<PrtgMonitoring_SendStringGetRequest_SendExpectedData>d__5.MoveNext() in C:\ProxyDocuments\Projects\QP\QP8.Infrastructure.Tests\PrtgMonitoringTests\PrtgMonitoringServiceTests.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _)

System.ArgumentException
Stream was not readable.
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Flurl.Http.Configuration.NewtonsoftJsonSerializer.Deserialize[T](Stream stream) in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\NewtonsoftJsonSerializer.cs:line 49
   at Flurl.Http.HttpResponseMessageExtensions.<ReceiveJson>d__0`1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\HttpResponseMessageExtensions.cs:line 32
```

Here PrtgMonitorService definition:
```
using System.Threading.Tasks;
using Flurl;
using Flurl.Http;
using QP8.Infrastructure.Logging.PrtgMonitoring.Data;
using QP8.Infrastructure.Logging.PrtgMonitoring.Interfaces;

namespace QP8.Infrastructure.Logging.PrtgMonitoring
{
    public class PrtgMonitoringService : IPrtgMonitoringService
    {
        private readonly string _host;
        private readonly string _identificationToken;

        public PrtgMonitoringService(string host, string identificationToken)
        {
            _host = host;
            _identificationToken = identificationToken;
        }

        public Url BaseUrl => _host.AppendPathSegment(_identificationToken);

        public async Task<PrtgHttpResponse> SendJsonRequest(object serializableLogDto)
        {
            return await BaseUrl.PostJsonAsync(serializableLogDto).ReceiveJson<PrtgHttpResponse>();
        }

        public async Task<PrtgHttpResponse> SendStringGetRequest(string logMessage)
        {
            return await BaseUrl.SetQueryParams(new { Content = logMessage }).GetJsonAsync<PrtgHttpResponse>();
        }

        public async Task<PrtgHttpResponse> SendStringPostRequest(string logMessage)
        {
            return await BaseUrl.PostStringAsync(logMessage).ReceiveJson<PrtgHttpResponse>();
        }
    }
}
```

**Comment by AuthorProxy** [comment]
Looks like the problem is in HttpTest, it failes even if move it localy to each method (the same as xunit did by default).
```
  [Fact]
        public async void PrtgMonitoring_SendStringGetRequest_SendExpectedData()
        {
            var _httpTest = new HttpTest();

            // Fixture setup
            var sut = _fixture.Create<PrtgMonitoringService>();

            // Exercise system
            await sut.SendStringGetRequest(SuccessRequestData);
            _httpTest.Dispose();
            // Verify outcome
            //_httpTest
            //    .ShouldHaveMadeACall()
            //    .WithVerb(HttpMethod.Get)
            //    .WithQueryParamValue("Content", SuccessRequestData);
        }

        [Fact]
        public async void PrtgMonitoring_SendStringPostRequest_SendExpectedData()
        {
            var _httpTest = new HttpTest();
            // Fixture setup
            var sut = _fixture.Create<PrtgMonitoringService>();

            // Exercise system
            await sut.SendStringPostRequest(ErrorRequestData);
            _httpTest.Dispose();

            // Verify outcome
            //_httpTest
            //    .ShouldHaveMadeACall()
            //    .WithVerb(HttpMethod.Post)
            //    .WithoutQueryParams()
            //    .WithRequestBody(SuccessRequestData);
        }
```

**Comment by tmenier** [comment]
Thank you for reporting, I've been able to reproduce this. The root cause is that when no fake responses have been configured with `HttpTest`, it will default to a 200 response with an empty body. A static instance of that response is re-used whenever needed. However, that response can only be JSON-deserialized once, due to the forward-only stream reading involved.

**The fix:**

I think I'll need to ditch the static instance of the empty response and create a new one as needed.

**The work-around:**

**Comment by tmenier** [comment]
Done and released to NuGet.
