### ISSUE TITLE
FlurlHttp .GetAsync() throw FlurlHttpException if response status code not success

### ISSUE THREAD

**Issue by rdcm** [tmenier/Flurl#238]
I have Uri like this `http://localhost:5000/v1/users/a44fad4a-db6f-4701-8bf0-3a036cdf6f46`
and following code:

```
        public async Task<(UserResponse user, HttpResponseMessage responseMessage)> GetUser(Guid userId, CancellationToken token = new CancellationToken())
        {
            var response = await _route.AppendPathSegment(userId).GetAsync(token);
            var user = await response.Content.ReadAsAsync<UserResponse>();
            
            return (user, response);
        }

```

When GetAsync( ... ) method invoked and response status code is not success, FlurlHttp throw  FlurlHttpException.

Its normal behavior for FlurlHttp or bug?

For example, i'am trying do this request with .Net HttpClient, all works fine.

StackTrace:

```
Flurl.Http.FlurlHttpException : GET http://localhost:5000/v1/users/4e611e31-2c59-4e36-94e9-020ac72d2fc1 failed with status code 404 (Not Found).
Response body:
User with id - '4e611e31-2c59-4e36-94e9-020ac72d2fc1' not found.
   at Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Flurl.Http.FlurlRequest.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TravalerService.Tests.ApiClient.UsersApi.<GetUser>d__2.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TravalerService.Tests.UsersTests.<Users_with_not_existing_id_not_found>d__0.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by tmenier** [comment]
That is by design, and you can customize it. Please read the docs:

http://tmenier.github.io/Flurl/error-handling/
