### ISSUE TITLE
ShouldHaveCalled WithContentType throws NullReferenceException if the request log contains requests with no content body

### ISSUE THREAD

**Issue by nlowe** [tmenier/Flurl#285]
I have a test method that makes a variety of requests. I want to assert that there was at least one `POST` to a URL with the specified content type:

```csharp
_http.ShouldHaveCalled($"{ApiTestEndpoint}/v1/institution")
        .WithVerb(HttpMethod.Post)
        .WithContentType("application/json");
```

However, in this same test run, I have a few POST requests to URL's with no request body. Because of this, the `Content` object on the `Request` is null, and throws when the assertion tries to evaluate the content type on a request in the log where no content was sent:

https://github.com/tmenier/Flurl/blob/79d6b3cd9e4f8ea43e1ca0b492aa203c48458cc0/src/Flurl.Http/Testing/HttpCallAssertion.cs#L192 

Working Request:

![image](https://user-images.githubusercontent.com/794251/37352303-5bc08ffe-26b3-11e8-883c-098326b44700.png)

Broken Request (no content):

![image](https://user-images.githubusercontent.com/794251/37352247-3a702cf6-26b3-11e8-87cf-e2e5e942b793.png)

Here's the full stack trace:

```csharp
System.NullReferenceException : Object reference not set to an instance of an object.
   at Flurl.Http.Testing.HttpCallAssertion.<>c__DisplayClass18_0.<WithContentType>b__0(HttpCall c)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Flurl.Http.Testing.HttpCallAssertion.With(Func`2 match)
   at Flurl.Http.Testing.HttpCallAssertion.WithContentType(String mediaType)
   at Athena.Importer.Tests.ProgramTests.<ImportsCoursees>d__10.MoveNext() in /home/nathan/projects/athena-scheduler/athena/test/Unit/Athena.Importer.Tests/ProgramTests.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

If acceptable (and if this isn't the intended behavior), I can open a pull request to fix this by inserting some null checks.

**Comment by tmenier** [comment]
didn't mean to close this quite yet, will upon final release
