### ISSUE TITLE
Tests rely on platform dependent line-endings and path seperators

### ISSUE THREAD

**Issue by nlowe** [tmenier/Flurl#286]
If I run the test suite on linux using the `netoreapp2.0` framework, 4 tests fail due to line endings and path seperators:

```csharp
Failed   exception_message_is_nice
Error Message:
   Expected string length 136 but was 132. Strings differ at index 64.
  Expected: "...status code 400 (Bad Request).\r\nRequest body:\r\n{"data":"ba..."
  But was:  "...status code 400 (Bad Request).\nRequest body:\n{"data":"bad"..."
  ---------------------------------------------^

Stack Trace:
   at Flurl.Test.Http.FlurlHttpExceptionTests.<exception_message_is_nice>d__0.MoveNext() in /home/nathan/projects/Flurl/Test/Flurl.Test/Http/FlurlHttpExceptionTests.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

Failed   can_build_multipart_content
Error Message:
   Expected string length 9 but was 19. Strings differ at index 0.
  Expected: "image.jpg"
  But was:  ""path\\to\\image.jpg""
  -----------^

Stack Trace:
   at Flurl.Test.Http.MultipartTests.can_build_multipart_content() in /home/nathan/projects/Flurl/Test/Flurl.Test/Http/MultipartTests.cs:line 40

Failed   can_download_file
Error Message:
   String lengths are both 61. Strings differ at index 50.
  Expected: "c:\\flurl-test-99d2dfce-556f-4952-a122-587ef41b409c\\google.txt"
  But was:  "c:\\flurl-test-99d2dfce-556f-4952-a122-587ef41b409c/google.txt"
  --------------------------------------------------------------^

Stack Trace:
   at Flurl.Test.Http.RealHttpTests.<can_download_file>d__2.MoveNext() in /home/nathan/projects/Flurl/Test/Flurl.Test/Http/RealHttpTests.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

Failed   can_download_file_with_default_name
Error Message:
   String lengths are both 65. Strings differ at index 50.
  Expected: "...lurl-test-44755f56-bd2e-49cf-9a86-8cfbf4e5ce5f\\www.google.com"
  But was:  "...lurl-test-44755f56-bd2e-49cf-9a86-8cfbf4e5ce5f/www.google.com"
  ------------------------------------------------------------^

Stack Trace:
   at Flurl.Test.Http.RealHttpTests.<can_download_file_with_default_name>d__3.MoveNext() in /home/nathan/projects/Flurl/Test/Flurl.Test/Http/RealHttpTests.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```

**Comment by tmenier** [comment]
I'd accept a PR for this if you wanted to tackle it. I'm guessing if you use `Environment.NewLine` and `Path.Combine` (or `Path.DirectorySeparatorChar`) you'll come up with something that works on all platforms. If you can verify on Linux, I'll verify on Windows.
