### ISSUE TITLE
Serialization Exception while unit testing

### ISSUE THREAD

**Issue by florinciubotariu** [tmenier/Flurl#338]
I am trying to mock a HTTP call using HttpTest.
Calls to ConfigurationManager.OpenExeConfiguration are throwing 
`SerializationException: Type is not resolved for member 'Flurl.Http.Testing.HttpTest,Flurl.Http, Version=2.3.1.0, Culture=neutral, PublicKeyToken=null.`

The problem is not only direct calls to `OpenExeConfiguration` but any libraries that may do that.
For example, `Elmah.ErrorLog.GetDefault` does exactly that, making us impossible to successfully unit test our methods.

I may be wrong, but as far as I understand, there are two AppDomains in play and a call to configuration manipulation may need to transfer context from one domain to another. Since HttpTest is not serializable, we can not transfer such data correctly making the upper exception to be thrown.

Example of stack trace (from the part where Elmah is called): 

     at System.AppDomain.get_Evidence()  
     at System.AppDomain.get_EvidenceNoDemand()  
     at System.AppDomain.get_Evidence()  
     at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)  
     at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)  
     at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)  
     at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
     at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
     at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
     at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
     at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
     at System.Configuration.ConfigurationManager.GetSection(String sectionName)
     at Elmah.SimpleServiceProviderFactory.CreateFromConfigSection(String sectionName)
     at Elmah.ErrorLog.GetDefaultImpl(HttpContext context)
     at Elmah.ServiceContainer.GetService(Type serviceType)
     at Elmah.ServiceCenter.FindService(Object context, Type serviceType)
     at Elmah.ServiceCenter.GetService(Object context, Type serviceType)
     at Elmah.ErrorLog.GetDefault(HttpContext context)

Possible work-around:
```
  public interface IMyHttpTest
  {
    void RespondWith(string v1, int v2, object p1, object p2);
  }

  [Serializable]
  public class MyHttpTest : HttpTest { }

  public class RemoteHttpTest : MarshalByRefObject, IMyHttpTest
  {
    private MyHttpTest myHttpTest = new MyHttpTest();

    public void RespondWith(string v1, int v2, object p1, object p2)
    {
      myHttpTest.RespondWith(v1, v2, p1, p2);
    }
  }
```

Then in the unit test:
```
var httpTest = new RemoteHttpTest();
httpTest.RespondWith("server error", 500, null, null);
```

**Comment by tmenier** [comment]
Does your work-around work? If so, I'd be willing to mark `HttpTest` with `[Serializable]` if that's really all there is to it. Are you aware of any potential pitfalls?

**Comment by tmenier** [comment]
Closing this as I haven't gotten a response. Marking `HttpTest` with `[Serializable]` is probably harmless, although I think something like Elmah should be stubbed out in unit tests. Feel free to re-open if this is still causing issues for you.
