### ISSUE TITLE
Flurl.Http 3.0.0-pre2 - System.MissingMethodException: Method not found: 'Void Flurl.QueryParamCollection.Merge(System.Object, Flurl.NullValueHandling)'.

### ISSUE THREAD

**Issue by tranb3r** [tmenier/Flurl#487]
Exception when using Flurl.Http 3.0.0-pre2:
```
System.MissingMethodException: Method not found: 'Void Flurl.QueryParamCollection.Merge(System.Object, Flurl.NullValueHandling)'.
   at Flurl.Http.Configuration.DefaultUrlEncodedSerializer.Serialize(Object obj)
   at Flurl.Http.GeneratedExtensions.PostUrlEncodedAsync(IFlurlRequest request, Object data, CancellationToken cancellationToken, HttpCompletionOption completionOption)
```
The code for this method does exist in the repo, but Flurl.Http still depends on Flurl 3.0.0-pre1.
Maybe you need to release Flurl 3.0.0-pre2 and update dependencies?

**Comment by tmenier** [comment]
Yikes, thanks for reporting. I'll get this fixed up soon.

**Comment by tmenier** [comment]
This should be fixed in the latest prerelease
