### ISSUE TITLE
New "Collection was modified; enumeration operation may not execute." in 3.0.1

### ISSUE THREAD

**Issue by eoftedal** [tmenier/Flurl#598]
It breaks under heavy load with:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare() in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs:line 1119
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext() in /_/src/System.Linq/src/System/Linq/Where.cs:line 218
   at Flurl.Http.FlurlRequest.SyncHeaders(HttpRequestMessage request)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
```

There is no line number for Flurl, but seeing how it's Where.cs line 218, it seems to be the here: https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/FlurlRequest.cs#L207

And that might make sense here:
```
			foreach (var header in Client.Headers.Where(h => !this.Headers.Contains(h.Name)))
				this.Headers.Add(header.Name, header.Value);

```
Isn't the second line updating something that might affect the condition in the Where and thus how it is evaluated?

**Comment by eoftedal** [comment]
May actually be related to https://github.com/tmenier/Flurl/issues/328#issuecomment-395997205
I'll investigate a bit more and see if it's actually headers being set on the client.

**Comment by eoftedal** [comment]
I believe this was the same as described in #328, where headers were sometimes set on the client. Will reopen if necessary
