### ISSUE TITLE
SyncHeaders is not thread safe

### ISSUE THREAD

**Issue by kamilbudziewski** [tmenier/Flurl#619]
Please provide a complete description of the bug and a code sample (or better yet, a unit test) that reproduces it.
I'm using Flurl for highly concurrent application and I'm getting this exception:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Flurl.Http.FlurlRequest.SyncHeaders(HttpRequestMessage request)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
```

I've briefly checked Flurl code and found this:
```
public INameValueList<string> Headers { get; } = new NameValueList<string>(false); // header names are case-insensitive https://stackoverflow.com/a/5259004/62600
...
private void SyncHeaders(HttpRequestMessage request) {
	// copy any client-level (default) headers to this request
	foreach (var header in Client.Headers.Where(h => !this.Headers.Contains(h.Name)))
		this.Headers.Add(header.Name, header.Value);

	// copy headers from FlurlRequest to HttpRequestMessage
	foreach (var header in Headers)
		request.SetHeader(header.Name, header.Value);

	// copy headers from HttpContent to FlurlRequest
	if (request.Content != null) {
		foreach (var header in request.Content.Headers)
			Headers.AddOrReplace(header.Key, string.Join(",", header.Value));
	}
}
```
From docs https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection?view=net-5.0

> Enumerating through a collection is intrinsically not a thread safe procedure. Even when a collection is synchronized, other threads can still modify the collection, which causes the enumerator to throw an exception. To guarantee thread safety during enumeration, you can either lock the collection during the entire enumeration or catch the exceptions resulting from changes made by other threads.

**Comment by tmenier** [comment]
Yep, looks legit. Thanks for reporting.

**Comment by malylemire1** [comment]
Same with QueryParamCollection 

System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at Flurl.QueryParamCollection.AddOrReplace(String name, Object value, Boolean isEncoded, NullValueHandling nullValueHandling)

**Comment by pborgmans** [comment]
Any idea when this fix will be included in a new version?

**Comment by cremor** [comment]
So this means that https://github.com/tmenier/Flurl/issues/328#issuecomment-395997205 is actually wrong and the last code snippet (that calls `WithHeader()` on the request object) is actually not thread safe either?

**Comment by tmenier** [comment]
This will tentatively be fixed in the next maintenance release. I can't promise a date yet but it's one of a small number of high-priority bug fixes I'd like to get released soon.

**Comment by tmenier** [comment]
@cremor Thanks for linking to that comment, I think it's actually still valid (except for the cookies gotcha, which is fixed). I wasn't suggesting that the collection is absolutely thread safe, just that if you stick to the pattern of setting headers at the _request_ level and not the _client_ level, you should be fine, because I can't imagine a scenario where you'd have multiple threads manipulating the same request.

@kamilbudziewski could you provide a sample of how your code is setting headers? Setting default headers on a `FlurlClient` should generally be done once after the client is created and before it's used to make calls. Have a look at the [comment](https://github.com/tmenier/Flurl/issues/328#issuecomment-395997205) that @cremor linked. Thread safety could probably still be improved here, but first I want to see if your code could be improved to avoid this.

**Comment by tmenier** [comment]
I'm hoping to hear back from @kamilbudziewski, @cremor, @pborgmans, or anyone who 👍'd this issue to get more details about how you encountered this error. It seems to me that a "collection was modified" exception could only happen here if you have one thread manipulating the client-level headers and another trying to use that client to make a call. I'm sure I can prevent this specific exception, but that doesn't make what you're doing here inherently thread-safe. Again, I'd suggest using request-level headers, or setting up all the client-level headers before you make any calls with it, otherwise you could end up with unpredictable behavior even if this exception were avoided.

**Comment by cremor** [comment]
I didn't encounter this myself. I only 👍'd because I thought it was an important issue.
But I didn't think too much about what is needed to actually trigger this. So if the exception can be prevented by better coding on the caller side, it's actually not that important for me.

**Comment by rcollette** [comment]
I'm going by memory here, but my recollection was that I was setting a bearer token in the Authorization header, which only changes periodically.  Therefore my initial thought was to set the header at the client level, rather than per request.   I wound up writing a sort of mini framework for managing expiring tokens.   While flexible, it is not necessarily succinct.  

```c#
    /// <summary>
    ///     Creates HTTPClient instances for Flurl which obtain and refresh tokens using an ITokenManager and sets the
    ///     Authorization: Bearer
    ///     header with the token, as well as setting common headers with
    ///     <see cref="HttpClientExtensions.SetupCommonHttpRequestHeaders" />
    /// </summary>
    /// <typeparam name="TTokenManager">An <see cref="ITokenManager" /> implementation</typeparam>
    public class FlurlBearerTokenManagingHttpClientFactory<TTokenManager> : DefaultHttpClientFactory where TTokenManager : ITokenManager
    {
        private readonly TTokenManager _tokenManager;

        public FlurlBearerTokenManagingHttpClientFactory(TTokenManager tokenManager)
        {
            _tokenManager = tokenManager;
        }

        public override System.Net.Http.HttpClient CreateHttpClient(HttpMessageHandler handler)
        {
            System.Net.Http.HttpClient? client = base.CreateHttpClient(handler);
            // This is an extension method, not part of HttpClient
            client.SetupCommonHttpRequestHeaders();
            return client;
        }

        public override HttpMessageHandler CreateMessageHandler()
        {
            HttpMessageHandler? innerHandler = base.CreateMessageHandler();
            return new BearerTokenMessageHandler(_tokenManager, innerHandler);
        }
    }
```

```c#
    /// <summary>
    ///     An <see cref="HttpMessageHandler" /> that uses an <see cref="ITokenManager" /> to set an Authorization: Bearer HTTP
    ///     header using a current bearer token.
    /// </summary>
    internal class BearerTokenMessageHandler : DelegatingHandler
    {
        private readonly ITokenManager _tokenManager;

        public BearerTokenMessageHandler(ITokenManager tokenManager, HttpMessageHandler innerHandler) : base(innerHandler)
        {
            _tokenManager = tokenManager;
        }

        protected override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            SetAuthorizationHeader(request).Wait(cancellationToken);
            return base.Send(request, cancellationToken);
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            await SetAuthorizationHeader(request);
            return await base.SendAsync(request, cancellationToken);
        }

        private async Task SetAuthorizationHeader(HttpRequestMessage request)
        {
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", await _tokenManager.GetTokenAsync());
        }
    }
```
```c#
    /// <summary>
    ///     Obtains and refreshes the Bearer token for API gateway clients.  Must be configured as a singleton service.
    ///     <remarks>
    ///         <para>This class must be configured as a Singleton for dependency injection.</para>
    ///         <para>
    ///             Requires a dependency injected implementation of IApiGatewayTokenClient which is responsible for fetching
    ///             the token. The IApiGateTokenClient implementation must be configured as a Singleton in Dependency Injection
    ///             configuration.
    ///         </para>
    ///     </remarks>
    /// </summary>
    public class ApiGatewayTokenManager : LockingValueFetcher<string>, IApiGatewayTokenManager
    {
        // TODO Move all ApiGateway code to a common NUGET package
        private readonly IApiGatewayTokenClient _client;
        private readonly ILogger<ApiGatewayTokenManager> _logger;
        private ApiGatewayToken? _commonApplicationServiceToken;
        private long? _tokenExpiryTime;

        public ApiGatewayTokenManager(IApiGatewayTokenClient apiGatewayTokenClient, ILogger<ApiGatewayTokenManager> logger)
        {
            _client = apiGatewayTokenClient;
            _logger = logger;
        }

        public async Task<string> GetTokenAsync()
        {
            _logger.LogDebug("Getting ApiGateway bearer token");
            string? value = await GetValueAsync();
            if (value == null)
            {
                // TODO Create an ApplicationException type
                throw new Exception("Unable to obtain a bearer token.");
            }
            _logger.LogDebug("Got ApiGateway bearer token");
            return value;
        }

        protected override bool IsValueReady()
        {
            return _commonApplicationServiceToken != null && DateTimeOffset.Now.ToUnixTimeMilliseconds() + 1000L <= _tokenExpiryTime;
        }

        protected override async Task<string> FetchValue()
        {
            _logger.LogDebug("Fetching new ApiGateway bearer token");
            _commonApplicationServiceToken = await _client.GetTokenAsync();
            if (_commonApplicationServiceToken == null)
            {
                throw new Exception("IApiGatewayTokenClient implementation returned null.");
            }
            if (string.IsNullOrEmpty(_commonApplicationServiceToken.AccessToken))
            {
                throw new InvalidOperationException("IApiGateTokenClient implementation returned an object with a null or empty AccessTokenProperty.");
            }
            _tokenExpiryTime = _commonApplicationServiceToken.IssuedAt + _commonApplicationServiceToken.ExpiresIn * 1000;
            _logger.LogDebug("Fetched new ApiGateway bearer token with expiry time {@LogContext}",
                new
                {
                    ApiGatewayBearerTokenExpiryTime = _tokenExpiryTime
                });
            return _commonApplicationServiceToken.AccessToken;
        }
    }
```
```c#
    /// <summary>
    ///     An abstraction that provides Singleton access to a value that may be obtained and updated periodically in an
    ///     asynchronous and thread-safe manner.
    /// </summary>
    /// <typeparam name="T">The type of the value that is fetched.</typeparam>
    public abstract class LockingValueFetcher<T>
    {

        private readonly SemaphoreSlim _lock = new(1);
        private T? _value;

        public async Task<T?> GetValueAsync()
        {
            if (IsValueReady())
            {
                return _value;
            }
            await _lock.WaitAsync();
            try
            {
                // Check again after waiting on the lock, another lock holder may have already updated the value.
                if (!IsValueReady())
                {
                    _value = await FetchValue();
                }
            }
            finally
            {
                _lock.Release();
            }
            return _value;
        }

        /**
         * An implementation that retrieves the value initially or subsequently if the IsValueReady method returns false.
         */
        protected abstract Task<T> FetchValue();

        /**
         * If false, the fetch value method is called to return an initial or refreshed value.
         */
        protected abstract bool IsValueReady();
    }
```

**Comment by tmenier** [comment]
Thanks @FossBrandon for providing a fix. I'd still strongly advise against manipulating the client while it's in use if at all possible, but obviously I don't want Flurl throwing exceptions where they're easily avoidable either, so hopefully this cures some pains in existing code where that's happening.

**Comment by tmenier** [comment]
Finally released, sorry for the particularly long delay on this one!
