### ISSUE TITLE
Method not found: PostJsonAsync

### ISSUE THREAD

**Issue by louieyu** [tmenier/Flurl#746]
Flurl.Http 3.2.4 run in the net framework 4.6.2 
Message:Method not found: 'System.Threading.Tasks.Task`1<Flurl.Http.IFlurlResponse> Flurl.Http.GeneratedExtensions.PostJsonAsync(System.String, System.Object, System.Threading.CancellationToken, System.Net.Http.HttpCompletionOption)'.
StackTrace:   at hg.model.erp.OdApiSync.SkuMappingSendApi.<SendAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at hg.model.erp.OdApiSync.SkuMappingSendApi.SendAsync(SkuSendRequest request)
   at hg.model.erp.OdApiSync.OdApiUtil.<SkuSendAsync>d__2.MoveNext() in D:\Test\SmService\hg.model.erp\OdApiSync\OdApiUtil.cs:line 63

**Comment by A9G-Data-Droid** [comment]
The reason for closing was not stated but it appears to be related to: https://github.com/tmenier/Flurl/issues/166
