### ISSUE TITLE
increasing timeout above 100s still ends request after 100s

### ISSUE THREAD

**Issue by springy76** [tmenier/Flurl#762]
I'm using `IFlurlRequest.WithTimeout(TimeSpan.FromMinutes(5))` (followed by `.PostAsync().ReceiveJson<bool>()`) to call a long running api endpoint (both client and server using NET7).

But after 100s the client gives up:

```
System.OperationCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> Flurl.Http.FlurlHttpTimeoutException: Call timed out: POST https://hostwithlongrunningoperation
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   --- End of inner exception stack trace ---
   ```

At server side I can see that `ControllerBase.HttpContext.RequestAborted` (of type `CancellationToken`) transissions to cancelled state at same time.

What could I have done wrong? (I only found similar issues with shorter timeouts than 100s so far)

**Comment by tmenier** [comment]
In your app, are you providing your own `HttpClient`, either by passing it to the `FlurlClient` constructor, or by implementing a [custom factory](https://flurl.dev/docs/configuration/#httpclientfactory)? If so, you'll need to set a greater value on `HttpClient.Timeout`, which defaults to 100s. Flurl [takes care of it for you](https://github.com/tmenier/Flurl/blob/master-3.x/src/Flurl.Http/Configuration/DefaultHttpClientFactory.cs#L21-L22) when it's in control of `HttpClient` construction, but you'll need to do it yourself when you're providing your own.

**Comment by springy76** [comment]
@tmenier thanks for the hint, I found a call to `IFlurlRequest.WithClient(new FlurlClient(precreatedHttpClient))` and now added an inifinite timeout to `precreatedHttpClient` (not tested yet, but I guess it does the trick).

Maybe you could introduce a public static method to prepare a given HttpClient to get "flurl compatible"? (currently just setting Timeout to infinite, would be called from `DefaultHttpClientFactory.CreateHttpClient` as well)

**Comment by tmenier** [comment]
Maybe, but there are bigger gotchas than this when providing your own client. Things like disabling native CookieContainer support and auto-redirects, necessary for Flurl to take over those things. And they can't be done after a client is already created. So I think this all comes down to better documentation.
