### ISSUE TITLE
System.EntryPointNotFoundException on PostJsonAsync

### ISSUE THREAD

**Issue by aiwaverse** [tmenier/Flurl#816]
I have encountered truly a strange error with Flurl on an extremely specific scenario, I have looked around for suggestions but haven't been able to find anything, so I'm posting this here as a bug in the hopes someone has an idea.
On my API running Framework 4.8 and the latest versions of Flurl and Flurl.Http, when I make a PostJsonAsync request, I encounter a System.EntryPointNotFoundException, like the following:
```
System.EntryPointNotFoundException: The entry point was not found.
   at System.Collections.Generic.IEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Flurl.Http.FlurlRequest.SyncHeaders(IFlurlClient client, IFlurlRequest request)
   at Flurl.Http.FlurlRequest.EnsureClient()
   at Flurl.Http.GeneratedExtensions.PostJsonAsync(IFlurlRequest request, Object body, HttpCompletionOption completionOption, CancellationToken cancellationToken)
```
This is the code that originated that:
```
response = await urlBitly
  .WithOAuthBearerToken(keyBitly)
  .PostJsonAsync(new
  {
    long_url = urlOriginal
  });
```
Using some detailed exception messages I was able to get the following:
```
EntryPointNotFoundException with TargetSite System.Collections.Generic.IEnumerator`1[T] GetEnumerator(), Module CommonLanguageRuntimeLibrary, Assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> System.EntryPointNotFoundException:  The entry point was not found.
   at System.Collections.Generic.IEnumerable`1.GetEnumerator()
```
The strangest part is that this doesn't happen if I test the code, if I run the code locally, or if I publish my API through Visual Studio, this exception only triggers if my Azure Agent builds it through the a pipeline on Azure.
As I stated, I have been stumped on this for months now, with nothing online of the same nature, and as this only happens with Flurl, maybe someone here has any idea!

**Comment by aiwaverse** [comment]
Well, soon after posting this we found out that for some reason the pipeline is using the wrong version of the dlls, despite there been no references to any other version, we found out the 4.0.0.0 version where the 4.0.2.0 should've been.
It is still strange but it doesn't seem related to Flurl, so I'll close this.
